version: "3"
services:
  nginx:
    build: ./dockers/nginx
    ports:
    - 80:80
    depends_on:
    - rails
    - react
    links:
    - rails
    - react
  rails:
    build:
      context: .
      dockerfile: ./dockers/rails/Dockerfile
    environment:
      - RAILS_ENV=production
    command: rails s
    ports:
      - 4567:3000
  react:
    build:
      context: .
      dockerfile: ./dockers/react/Dockerfile
    command: node server.js
    ports:
      - 8080:8080
