version: "3"
services:
  rails:
    restart: always
    build:
      context: .
      dockerfile: ./dockers/rails/Dockerfile
    environment:
      - RAILS_ENV=production
      - SECRET_KEY_BASE=rio32pqir23r2h3ur23prh2u13r213r
    command: rails s
    ports:
      - 3000:3000
  react:
    restart: always
    build:
      context: .
      dockerfile: ./dockers/react/Dockerfile
    command: node server.js
    ports:
      - 8080:8080
