version: "3"
services:
  nginx:
    build: ./dockers/nginx
    ports:
    - 80:80
    depends_on:
    - rails
    - react
    links:
    - rails
    - react
  rails:
    build:
      context: .
      dockerfile: ./dockers/rails/Dockerfile
    environment:
      - RAILS_ENV=production
      - SECRET_KEY_BASE=rio32pqir23r2h3ur23prh2u13r213r
    command: rails s
    expose:
      - 3000
  react:
    build:
      context: .
      dockerfile: ./dockers/react/Dockerfile
    command: node server.js
    expose:
      - 8080
